name: Backend Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean install
        working-directory: back

      - name: Run Tests
        run: mvn -B test
        working-directory: back

      - name: Generate JaCoCo Report
        run: mvn jacoco:report
        working-directory: back

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: back/target/site/jacoco/
