name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar

      - name: Build Docker Image
        run: |
          docker build -t bobapp-frontend -f Dockerfile.frontend .
          docker build -t bobapp-backend -f Dockerfile.backend .

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag bobapp-frontend $DOCKER_USERNAME/bobapp-frontend:latest
          docker tag bobapp-backend $DOCKER_USERNAME/bobapp-backend:latest
          docker push $DOCKER_USERNAME/bobapp-frontend:latest
          docker push $DOCKER_USERNAME/bobapp-backend:latest
