name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in root directory
      run: ls -la

    - name: List files in front directory
      run: ls -la front

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Vous pouvez spécifier la version de Node.js que vous utilisez

    - name: Install dependencies
      run: npm install
      working-directory: front

    - name: Run Tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      working-directory: front
