name: Complete CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11 (for Backend)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build Backend with Maven
      run: mvn clean install
      working-directory: back

    - name: Run Backend Tests
      run: mvn test
      working-directory: back

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: back
        file: Dockerfile           # Assurez-vous que le fichier Dockerfile est présent dans le répertoire back
        push: false                # Changez à false ici puisque nous ne voulons pas faire le push tout de suite
        tags: local/bobapp:latest  # Taguez l'image localement pour une utilisation ultérieure

  push:
    runs-on: ubuntu-latest
    needs: build                # Assurez-vous que cette tâche ne commence qu'après la tâche de construction

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag local/bobapp:latest ${{ secrets.DOCKER_USERNAME }}/bobapp:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/bobapp:latest
