name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Frontend
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: front
      - name: Build and test frontend
        run: npm run build && npm run test
        working-directory: front

      # Backend
      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '3.8.6'
      - name: Build and test backend
        run: mvn clean install
        working-directory: back

      # SonarQube
      - name: SonarQube analysis
        uses: sonarcloud/sonarcloud-github-action@v1
        with:
          sonar-cloud-token: ${{ secrets.SONARCLOUD_TOKEN }}
          sonar-organization: ${{ secrets.SONARCLOUD_ORGANIZATION }}
          sonar-project-key: ${{ secrets.SONARCLOUD_PROJECT_KEY }}
          sonar-branch: main
          sonar-source: back/src/main/java
          sonar-test: back/src/test/java
          sonar-coverage: back/target/site/jacoco
