name: Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Compile Backend
        run: mvn compile
        working-directory: back
      
      - name: Run Tests for Backend
        run: mvn test
        working-directory: back
      
      - name: Set up Node.js (for Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies for Frontend
        run: npm install --legacy-peer-deps
        working-directory: front
      
      - name: Run Tests for Frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: front
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.6.0
        with:
          args: >
            -Dsonar.projectKey=myprojectkey
            -Dsonar.organization=myorganization
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.coverage.excludes=**/test/** # Exclure les fichiers de test si nécessaire

      - name: Check Quality Gate
        run: |
          echo "Checking SonarCloud Quality Gate..."
          QUALITY_GATE_STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=myprojectkey" | jq -r '.projectStatus.status')
          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
            echo "Quality Gate failed: $QUALITY_GATE_STATUS"
            exit 1
          else
            echo "Quality Gate passed!"
          fi
