name: Quality Check

on:
push:
branches:
- main
pull_request:
branches:
- main
workflow_dispatch: # Permet le déclenchement manuel

jobs:
analyze-code:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v4

- name: Set up JDK 11
uses: actions/setup-java@v3
with:
java-version: '11'
distribution: 'adopt'

- name: Set up Node.js
uses: actions/setup-node@v3
with:
node-version: '18'

- name: Build Backend
run: mvn clean package
working-directory: back

- name: Install Frontend Dependencies
run: npm install --legacy-peer-deps
working-directory: front

- name: Build Frontend
run: npm run build
working-directory: front

- name: Run SonarCloud Analysis
uses: sonarsource/sonarcloud-github-action@v2
with:
projectBaseDir: .
args: >
-Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
-Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
-Dsonar.token=${{ secrets.SONAR_TOKEN }}
-Dsonar.sources=back/src,front/src
-Dsonar.tests=back/src/test,front/src
-Dsonar.test.inclusions=back/src/test/java/com/openclassrooms/bobapp/BobappApplicationTests.java,front/src/test.ts
-Dsonar.inclusions=**/*.java,**/*.js,**/*.ts
-Dsonar.java.binaries=back/target/classes
env:
SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
JAVA_HOME: ${{ runner.tool_cache }}/jdk/11
