name: CI - Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install --legacy-peer-deps
        working-directory: front

      - name: Verify package.json
        run: cat front/package.json

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Backend Dependencies
        run: mvn clean install
        working-directory: back

      - name: Nettoyer les dépendances
        run: |
          npm cache clean --force
          mvn clean

      - name: Exécuter les tests unitaires
        run: |
          npm run test:unit
          mvn test

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=back/src,front/src
            -Dsonar.tests=back/src/test,front/src
            -Dsonar.inclusions=**/*.java,**/*.js,**/*.ts
            -Dsonar.java.binaries=back/target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ${{ runner.tool_cache }}/jdk/11

      - name: Vérifier les résultats de l'analyse SonarCloud
        run: |
          if [ $(sonarcloud status) -eq 1 ]; then
            echo "Analyse SonarCloud échouée"
            exit 1
          else
            echo "Analyse SonarCloud réussie"
          fi

      - name: Envoyer les résultats de l'analyse à Slack
        uses: slack/github-actions@v1
        with:
          channel: '#my-channel'
          message: 'Analyse SonarCloud terminée'
