name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11 (for Backend)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Backend
        run: mvn compile
        working-directory: back
      - name: Test Backend Unitaires
        run: mvn test
        working-directory: back
      - name: Test Backend d'Intégration
        run: mvn integration-test
        working-directory: back
      - name: Set up Node.js (for Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Installer dépendances
        run: npm install --legacy-peer-deps
        working-directory: front
      - name: Compiler Frontend
        run: npm run build
        working-directory: front
      - name: Tester Frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: front
      - name: Télécharger les archives des tests
        uses: actions/download-artifact@v4
        with:
          name: test-archives
          path: ${{ github.workspace }}/back/test-reports
      - name: Afficher les rapports de test
        run: |
          echo "Rapports de test:"
          ls -l ${{ github.workspace }}/back/test-reports
          cat ${{ github.workspace }}/back/test-reports/*.xml
        shell: bash
