name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11 (for Backend)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Backend with Maven
        run: mvn clean install
        working-directory: back
      - name: Run Backend Tests
        run: mvn test
        working-directory: back
      - name: Generate Backend Test Report
        run: mvn jacoco:report
        working-directory: back
      - name: Upload Backend Test Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: back/target/site/jacoco/
      - name: SonarQube Scan
        uses: sonarcloud/sonarcloud-github-action@v1
        with:
          sonar-cloud-token: ${{ secrets.SONARCLOUD_TOKEN }}
          sonar-organization: ${{ secrets.SONARCLOUD_ORGANIZATION }}
          sonar-project-key: ${{ secrets.SONARCLOUD_PROJECT_KEY }}
          sonar-branch: main
          sonar-source: back/src/main/java
          sonar-test: back/src/test/java
          sonar-coverage: back/target/site/jacoco

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js (for Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        run: npm install --legacy-peer-deps
        working-directory: front
      - name: Build Frontend
        run: npm run build
        working-directory: front
      - name: Run Frontend Tests (with Headless Chrome)
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: front
