name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Backend
        run: |
          cd back
          mvn clean package
      - name: Run Backend Tests
        run: |
          cd back
          mvn test
      - name: Generate Backend Test Report
        run: |
          cd back
          mvn jacoco:report
      - name: Upload Backend Test Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: back/target/site/jacoco/

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        run: |
          cd front
          npm install --legacy-peer-deps
      - name: Build Frontend
        run: |
          cd front
          npm run build
      - name: Run Frontend Tests
        run: |
          cd front
          npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Upload Frontend Test Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-report
          path: front/test-results.xml

  test-sonar:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
   - name: Run SonarCloud Analysis
  uses: sonarsource/sonarcloud-github-action@v2
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
    SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  with:
    projectBaseDir: .
    args: >
      -Dsonar.sources=back/src,front/src 
      -Dsonar.tests=back/src/test,front/src 
      -Dsonar.test.inclusions=back/src/test/java/com/openclassrooms/bobapp/BobappApplicationTests.java,front/src/test.ts 
      -Dsonar.inclusions=**/*.java,**/*.js,**/*.ts

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ${{ runner.tool_cache }}/jdk/11
