name: CI - Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Choisissez votre version Node.js ici

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        working-directory: front  # Assurez-vous que ce répertoire est où se trouve le package.json

      - name: Vérifier package.json
        run: cat front/package.json  # Cela affichera le contenu du package.json

      - name: Run ESLint
        run: npm run lint
        working-directory: front  # Cela indiquerait à GitHub Actions d'exécuter le script dans le bon répertoire
      
      - name: Run Frontend Tests
        run: npm run test -- --watch=false
        working-directory: front  # Assurez-vous là aussi de pointer vers le bon répertoire
