# test.yml
name: Test Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11 (for Backend)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Backend
        run: mvn compile
        working-directory: back
      - name: Test Backend Unitaires
        run: mvn test
        working-directory: back
      - name: Test Backend d'Intégration
        run: mvn integration-test
        working-directory: back
      - name: Lancer une instance Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Lancer une instance Docker
        run: |
          docker build -t local/bobapp:latest back
          docker run -d -p 8080:8080 --name bobapp local/bobapp:latest
      - name: Attendre que l'instance Docker soit prête
        run: |
          sleep 10
      - name: Stocker les rapports de test
        run: |
          mkdir -p back/target
          docker exec -it bobapp mvn test -Dmaven.test.redirectTestOutputToFile=true
          docker cp bobapp:/app/back/target/surefire-reports back/target
      - name: Télécharger les rapports de test
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: back/target
