name: CI - Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adaptez selon la version de Node.js que vous utilisez

      - name: Install Frontend Dependencies
        run: npm install --legacy-peer-deps
        working-directory: front  # Changez ce chemin si nécessaire

      - name: Verify package.json
        run: cat front/package.json  # Pour vérifier le contenu du package.json

