name: CI - Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check-frontend:
    name: Quality Check Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install --legacy-peer-deps
        working-directory: front

      - name: Run ESLint
        run: npm run lint
        working-directory: front

      - name: Run Frontend Tests
        run: npm run test -- --watch=false
        working-directory: front
