name: CI - Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check-frontend:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install --legacy-peer-deps
        working-directory: front

      - name: Verify package.json
        run: |
          cat front/package.json

      - name: SonarQube Scan Frontend
        uses: sonarcloud/sonarcloud-github-action@v3
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.inclusions=**/*.js,**/*.ts
            -Dsonar.exclusions=**/node_modules/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality-check-backend:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Backend Dependencies
        run: mvn clean install
        working-directory: back

      - name: Verify pom.xml
        run: |
          cat back/pom.xml

      - name: SonarQube Scan Backend
        uses: sonarcloud/sonarcloud-github-action@v3
        with:
          projectBaseDir: back
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.inclusions=**/*.java
            -Dsonar.exclusions=**/target/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
