name: Front-End and Back-End Tests

on:
  push:
    branches:
      - main

jobs:
  front-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        run: |
          npm install

      - name: Run front-end tests
        run: |
          npm run test

      - name: Run front-end linting
        run: |
          npm run lint

      - name: Upload front-end test report
        uses: actions/upload-artifact@v2
        with:
          name: front-end-test-report
          path: /github/workspace/coverage/front-end

  back-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and install back-end
        run: |
          mvn clean install

      - name: Run back-end tests
        run: |
          mvn test

      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: /github/workspace/back
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=/github/workspace/back/src
            -Dsonar.test.inclusions=/github/workspace/back/src/test/java/**
            -Dsonar.java.binaries=/github/workspace/back/target/classes
            -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

      - name: Upload back-end test report
        uses: actions/upload-artifact@v2
        with:
          name: back-end-test-report
          path: /github/workspace/back/target/site/test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        run: |
          npm install

      - name: Run end-to-end tests
        run: |
          npm run e2e

      - name: Upload end-to-end test report
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-report
          path: /github/workspace/coverage/e2e
